In [31]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, ElasticNet, Ridge, Lasso
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score

from sklearn.impute import SimpleImputer 

import os
os.chdir("D:/Machine_Learning/Datasets") #fetch the dataset from the folder

In [2]:
housing = pd.read_csv("Housing.csv")
housing

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [3]:
dum_hous = pd.get_dummies(housing, drop_first=True)
X = dum_hous.drop('price', axis=1)
y = dum_hous['price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=26)

In [5]:
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred =lr.predict(X_test)
print("R2 =",r2_score(y_test,y_pred))

R2 = 0.6791781818067918

In [8]:
alphas=np.linspace(0.001, 5)
scores=[]

for a in alphas:
    lasso = Lasso(alpha = a)
    lasso.fit(X_train, y_train)
    y_pred = lasso.predict(X_test)
    scores.append([a, r2_score(y_test, y_pred)])
    
df_scores = pd.DataFrame(scores, columns=['alpha','score'])
df_scores.sort_values('score', ascending=False).head()

      alpha     score
0  0.001000  0.679178
1  0.103020  0.679174
2  0.205041  0.679171
3  0.307061  0.679167
4  0.409082  0.679163

In [9]:
alphas=np.linspace(0.001, 5)
scores=[]

for a in alphas:
    ridge = Ridge(alpha = a)
    ridge.fit(X_train, y_train)
    y_pred = ridge.predict(X_test)
    scores.append([a, r2_score(y_test, y_pred)])
    
df_scores = pd.DataFrame(scores, columns=['alpha','score'])
df_scores.sort_values('score', ascending=False).head()

      alpha     score
0  0.001000  0.679177
1  0.103020  0.679104
2  0.205041  0.679030
3  0.307061  0.678956
4  0.409082  0.678880

In [10]:
alphas=np.linspace(0.001, 5, 20)
ratio=np.linspace(0, 1, 20)
scores=[]

for a in alphas:
    for r in ratio:
        e1 = ElasticNet(alpha = a, l1_ratio = r)
        e1.fit(X_train, y_train)
        y_pred = e1.predict(X_test)
        scores.append([a, r, r2_score(y_test, y_pred)])
        
df_scores = pd.DataFrame(scores, columns=['alpha','score', 'l1_ratio'])
df_scores.sort_values('score', ascending=False).head()

C:\Users\PGCP-AI\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.637e+10, tolerance: 2.726e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.255e+10, tolerance: 2.726e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.931e+10, tolerance: 2.726e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.338e+10, tolerance: 2.726e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.617e+10, tolerance: 2.726e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.820e+10, tolerance: 2.726e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.977e+10, tolerance: 2.726e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.101e+10, tolerance: 2.726e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.201e+10, tolerance: 2.726e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.285e+10, tolerance: 2.726e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.356e+10, tolerance: 2.726e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.416e+10, tolerance: 2.726e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.468e+10, tolerance: 2.726e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.514e+10, tolerance: 2.726e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.554e+10, tolerance: 2.726e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.590e+10, tolerance: 2.726e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.622e+10, tolerance: 2.726e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.650e+10, tolerance: 2.726e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.676e+10, tolerance: 2.726e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.700e+10, tolerance: 2.726e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(

        alpha  score  l1_ratio
19   0.001000    1.0  0.679178
399  5.000000    1.0  0.678996
159  1.842737    1.0  0.679112
239  2.895158    1.0  0.679074
79   0.790316    1.0  0.679150

# tst_housing dataset

In [42]:
tst = pd.read_csv("tst_Housing.csv")
tst

,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,5600,3,1,2,yes,no,yes,no,no,1,no
1,4355,2,1,1,yes,no,no,no,no,0,no
2,3412,3,1,1,yes,no,no,no,no,0,no
3,6666,2,2,2,yes,yes,no,no,no,0,no

In [43]:
dum_tst = pd.get_dummies(tst, drop_first=True)

In [44]:
dum_tst

   lotsize  bedrooms  bathrms  stories  garagepl  recroom_yes  fullbase_yes
0     5600         3        1        2         1        False          True
1     4355         2        1        1         0        False         False
2     3412         3        1        1         0        False         False
3     6666         2        2        2         0         True         False

# Concrete Dataset

In [46]:
os.chdir("D:/Machine_Learning/Cases/Concrete_Strength")

In [47]:
conc_data = pd.read_csv('Concrete_Data.csv')
conc_data

,Cement,Blast,Fly,Water,Superplasticizer,Coarse,Fine,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.40

In [48]:
dum_conc = pd.get_dummies(conc_data, drop_first=True)
X = dum_conc.drop('Strength', axis=1)
y = dum_conc['Strength']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=26)

In [49]:
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred =lr.predict(X_test)
print("R2 =",r2_score(y_test,y_pred))

R2 = 0.6181464728464399

In [50]:
alphas=np.linspace(0.001, 5)
scores=[]

for a in alphas:
    lasso = Lasso(alpha = a)
    lasso.fit(X_train, y_train)
    y_pred = lasso.predict(X_test)
    scores.append([a, r2_score(y_test, y_pred)])
    
df_scores = pd.DataFrame(scores, columns=['alpha','score'])
df_scores.sort_values('score', ascending=False).head()

       alpha     score
23  2.347469  0.619196
24  2.449490  0.619195
22  2.245449  0.619192
25  2.551510  0.619192
21  2.143429  0.619185

In [51]:
alphas=np.linspace(0.001, 5)
scores=[]

for a in alphas:
    ridge = Ridge(alpha = a)
    ridge.fit(X_train, y_train)
    y_pred = ridge.predict(X_test)
    scores.append([a, r2_score(y_test, y_pred)])
    
df_scores = pd.DataFrame(scores, columns=['alpha','score'])
df_scores.sort_values('score', ascending=False).head()

       alpha     score
49  5.000000  0.618149
48  4.897980  0.618149
47  4.795959  0.618149
46  4.693939  0.618149
45  4.591918  0.618149

In [ ]:
alphas=np.linspace(0.001, 5, 20)
ratio=np.linspace(0, 1, 20)
scores=[]

for a in alphas:
    for r in ratio:
        e1 = ElasticNet(alpha = a, l1_ratio = r)
        e1.fit(X_train, y_train)
        y_pred = e1.predict(X_test)
        scores.append([a, r, r2_score(y_test, y_pred)])
        
df_scores = pd.DataFrame(scores, columns=['alpha', 'score', 'l1_ratio'])
df_scores.sort_values('score', ascending=False).head()

In [53]:
tst = pd.read_csv("testConcrete.csv")
tst

    Cement  Blast  Fly  Water  Superplasticizer  Coarse  Fine  Age
0      495    120    0    155                 5     866   884   75
1      262    129    0    271                 2     808   787  174
2      201     48    1    215                 5     807   839  113
3      329    141    0    286                 1     881   823  229
4      354     14    0    129                 2     839   847  210
5      150     23   23    114                 4     883   638   36
6      480     64    0    292                 3     896   776  180
7      393     49   82    132                 1     887   830  271
8      284     63    1    138                 1     804   725   44
9      206     38    0    103                 2     818   719  191
10     247     64   26    175                 2     822   898  183
11     223    102    0    110                 2     808   854  270
12     457     89    0    289                 3     829   865  190
13     125     93    0    200                 5     893   671  113

# Inferencing

In [55]:
bm = ElasticNet(alpha= 5, l1_ratio= 0.263158)
bm.fit(X, y)

ElasticNet(alpha=5, l1_ratio=0.263158)

In [56]:
tst['Predicted'] = bm.predict(tst)
tst

    Cement  Blast  Fly  Water  Superplasticizer  Coarse  Fine  Age  Predicted
0      495    120    0    155                 5     866   884   75  69.422232
1      262    129    0    271                 2     808   787  174  30.541413
2      201     48    1    215                 5     807   839  113  19.542512
3      329    141    0    286                 1     881   823  229  44.603082
4      354     14    0    129                 2     839   847  210  60.427137
5      150     23   23    114                 4     883   638   36  19.549537
6      480     64    0    292                 3     896   776  180  47.742368
7      393     49   82    132                 1     887   830  271  82.354604
8      284     63    1    138                 1     804   725   44  34.162597
9      206     38    0    103                 2     818   719  191  45.433335
10     247     64   26    175                 2     822   898  183  44.538800
11     223    102    0    110                 2     808   854  270  63.802756
12     457     89    0    289                 3     829   865  190  49.884783
13     125     93    0    200                 5     893   671  113  15.980987

In [57]:
dum_tst['driveway_yes'] = True
dum_tst['gashw_yes'] = False
dum_tst['airco_yes'] = False
dum_tst['prefarea_yes'] = False
dum_tst = dum_tst[['lotsize','bedrooms', 'bathrms','stories','garagepl','driveway_yes','recroom_yes',
                   'fullbase_yes','gashw_yes','airco_yes','prefarea_yes']]

dum_tst.columns

Index(['lotsize', 'bedrooms', 'bathrms', 'stories', 'garagepl', 'driveway_yes',
       'recroom_yes', 'fullbase_yes', 'gashw_yes', 'airco_yes',
       'prefarea_yes'],
      dtype='str')