In [42]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score,roc_curve,RocCurveDisplay
from sklearn.metrics import recall_score, precision_score, classification_report,log_loss
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder,StandardScaler,LabelEncoder
from sklearn.compose import  ColumnTransformer
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score, roc_curve, RocCurveDisplay, roc_auc_score
import os

In [43]:
sonar=pd.read_csv(r'../sonar.csv')
sonar

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V52,V53,V54,V55,V56,V57,V58,V59,V60,Class
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,0.0187,0.0346,0.0168,0.0177,0.0393,0.1630,0.2028,0.1694,0.2328,0.2684,...,0.0116,0.0098,0.0199,0.0033,0.0101,0.0065,0.0115,0.0193,0.0157,M
204,0.0323,0.0101,0.0298,0.0564,0.0760,0.0958,0.0990,0.1018,0.1030,0.2154,...,0.0061,0.0093,0.0135,0.0063,0.0063,0.0034,0.0032,0.0062,0.0067,M
205,0.0522,0.0437,0.0180,0.0292,0.0351,0.1171,0.1257,0.1178,0.1258,0.2529,...,0.0160,0.0029,0.0051,0.0062,0.0089,0.0140,0.0138,0.0077,0.0031,M
206,0.0303,0.0353,0.0490,0.0608,0.0167,0.1354,0.1465,0.1123,0.1945,0.2354,...,0.0086,0.0046,0.0126,0.0036,0.0035,0.0034,0.0079,0.0036,0.0048,M
207,0.0260,0.0363,0.0136,0.0272,0.0214,0.0338,0.0655,0.1400,0.1843,0.2354,...,0.0146,0.0129,0.0047,0.0039,0.0061,0.0040,0.0036,0.0061,0.0115,M

In [44]:
X = sonar.drop("Class", axis=1)
y = sonar['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=26, stratify=y)
le = LabelEncoder()
sonar['Class']=le.fit(sonar['Class'])
y_pred_prob = lr.predict_proba(X_test)
le.classes_

array(['M', 'R'], dtype=object)

In [45]:
lr = LogisticRegression()
lr.fit(X_train, y_train)

y_pred_prob = lr.predict_proba(X_test)
log_loss(y_test, y_pred_prob)
# score = log_lo(y_test, y_pred_prob[:, 1])
# disp = RocCurveDisplay(fpr=fpr, tpr=tpr, roc_auc=score, estimator_name="ROC CURVE")

# disp.plot()
# plt.show()

0.4835944820149943

In [ ]:
solvers = ["lbfgs", "liblinear", "newton-cg", "newton-cholesky", "sag", "saga"]
Cs = np.linspace(0.001, 5, 20)
scores = []

for s in solvers:
    for c in Cs:
        lr = LogisticRegression(solver=s, C=c, max_iter=1000) 
        lr.fit(X_train, y_train)
        y_pred_PROB = lr.predict(X_test)
        f1 = f1_score(y_test, y_pred, pos_label='R')
        scores.append([s, c, f1])
df_scores = pd.DataFrame(scores, columns=['solver', 'C', 'score'])
df_scores.sort_values('score', ascending=True)

              solver         C     score
3              lbfgs  0.790316  0.833333
2              lbfgs  0.527211  0.833333
5              lbfgs  1.316526  0.833333
4              lbfgs  1.053421  0.833333
6              lbfgs  1.579632  0.833333
..               ...       ...       ...
20         liblinear  0.001000  0.000000
40         newton-cg  0.001000  0.000000
60   newton-cholesky  0.001000  0.000000
80               sag  0.001000  0.000000
100             saga  0.001000  0.000000

[120 rows x 3 columns]

IndentationError: unexpected indent (353908890.py, line 9)

IndentationError: unexpected indent (353908890.py, line 9)

IndentationError: unexpected indent (353908890.py, line 9)

IndentationError: unexpected indent (353908890.py, line 9)

IndentationError: unexpected indent (4101879539.py, line 9)

IndentationError: unexpected indent (4101879539.py, line 9)

    solver         C  score
0    lbfgs  0.001000    0.8
1    lbfgs  0.264105    0.8
2    lbfgs  0.527211    0.8
3    lbfgs  0.790316    0.8
4    lbfgs  1.053421    0.8
..     ...       ...    ...
115   saga  3.947579    0.8
116   saga  4.210684    0.8
117   saga  4.473789    0.8
118   saga  4.736895    0.8
119   saga  5.000000    0.8

[120 rows x 3 columns]

    solver         C  score
0    lbfgs  0.001000    0.8
1    lbfgs  0.264105    0.8
2    lbfgs  0.527211    0.8
3    lbfgs  0.790316    0.8
4    lbfgs  1.053421    0.8
..     ...       ...    ...
115   saga  3.947579    0.8
116   saga  4.210684    0.8
117   saga  4.473789    0.8
118   saga  4.736895    0.8
119   saga  5.000000    0.8

[120 rows x 3 columns]

    solver         C  score
0    lbfgs  0.001000    0.8
1    lbfgs  0.264105    0.8
2    lbfgs  0.527211    0.8
3    lbfgs  0.790316    0.8
4    lbfgs  1.053421    0.8
..     ...       ...    ...
115   saga  3.947579    0.8
116   saga  4.210684    0.8
117   saga  4.473789    0.8
118   saga  4.736895    0.8
119   saga  5.000000    0.8

[120 rows x 3 columns]