In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import  train_test_split
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error,root_mean_squared_error
import os
from sklearn.preprocessing import PolynomialFeatures
from sklearn.impute import SimpleImputer

In [2]:
os.chdir("C:/Users/PGCP-AI/Downloads/Cases/Chemical Process Data")

In [3]:
chem=pd.read_csv("ChemicalProcess.csv")
chem

,Yield,BiologicalMaterial01,BiologicalMaterial02,BiologicalMaterial03,BiologicalMaterial04,BiologicalMaterial05,BiologicalMaterial06,BiologicalMaterial07,BiologicalMaterial08,BiologicalMaterial09,...,ManufacturingProcess36,ManufacturingProcess37,ManufacturingProcess38,ManufacturingProcess39,ManufacturingProcess40,ManufacturingProcess41,ManufacturingProcess42,ManufacturingProcess43,ManufacturingProcess44,ManufacturingProcess45
0,38.00,6.25,49.58,56.97,12.74,19.51,43.73,100.0,16.66,11.44,...,0.019,0.5,3,7.2,NaN,NaN,11.6,3.0,1.8,2.4
1,42.44,8.01,60.97,67.48,14.65,19.36,53.14,100.0,19.04,12.55,...,0.019,2.0,2,7.2,0.1,0.15,11.1,0.9,1.9,2.2
2,42.03,8.01,60.97,67.48,14.65,19.36,53.14,100.0,19.04,12.55,...,0.018,0.7,2,7.2,0.0,0.00,12.0,1.0,1.8,2.3
3,41.42,8.01,60.97,67.48,14.65,19.36,53.14,100.0,19.04,12.55,...,0.018,1.2,2,7.2,0.0,0.00,10.6,1.1,1.8,2.1
4,42.49,7.47,63.33,72.25,14.02,17.91,54.66,100.0,18.22,12.80,...,0.017,0.2,2,7.3,0.0,0.00,11.0,1.1,1.7,2.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,39.66,6.71,56.32,66.19,12.35,20.02,50.26,100.0,17.54,12.50,...,NaN,2.3,0,0.0,0.0,0.00,0.0,0.6,0.0,0.0
172,39.68,6.87,56.74,66.61,12.55,20.18,50.80,100.0,17.48,12.41,...,NaN,1.0,0,0.0,0.0,0.00,0.0,0.6,0.0,0.0
173,42.23,7.50,58.41,68.30,13.33,20.81,52.96,100.0,17.23,12.04,...,NaN,1.3,0,0.0,0.0,0.00,0.0,0.6,0.0,0.0
174,38.48,7.53,58.36,69.25,14.35,20.57,51.31,100.0,17.87,12.77,...,NaN,2.3,0,0.0,0.0,0.00,0.0,0.5,0.0,0.0
175,39.49,7.53,58.36,69.25,14.35,20.57,51.31,100.0,17.87,12.77,...,NaN,0.9,0,0.0,0.0,0.00,0.0,0.6,0.0,0.0

In [4]:
chem.shape

(176, 58)

In [5]:
chem.isnull()

,Yield,BiologicalMaterial01,BiologicalMaterial02,BiologicalMaterial03,BiologicalMaterial04,BiologicalMaterial05,BiologicalMaterial06,BiologicalMaterial07,BiologicalMaterial08,BiologicalMaterial09,...,ManufacturingProcess36,ManufacturingProcess37,ManufacturingProcess38,ManufacturingProcess39,ManufacturingProcess40,ManufacturingProcess41,ManufacturingProcess42,ManufacturingProcess43,ManufacturingProcess44,ManufacturingProcess45
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
172,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
173,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
174,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
175,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False

In [6]:
chem["Yield"].isnull().sum()

np.int64(0)

In [7]:
chem.isnull().sum().sum()

np.int64(106)

In [8]:
os.chdir("C:/Users/PGCP-AI/Downloads/Datasets/Datasets")
job = pd.read_csv('JobSalary2.csv')
job

   S_No  Computer  Marketing  Engineer
0     1      84.0       55.0        75
1     2      90.0       53.0        70
2     3      63.0        NaN        88
3     4       NaN       50.0        77
4     5      63.0       41.0        89
5     6      75.0       54.0        85
6     7       NaN       51.0        96
7     8      77.0       64.0       105

In [9]:
const_imp = SimpleImputer(strategy = 'constant',fill_value=60).set_output(transform="pandas")
const_imp.fit_transform(job)

   S_No  Computer  Marketing  Engineer
0   1.0      84.0       55.0      75.0
1   2.0      90.0       53.0      70.0
2   3.0      63.0       60.0      88.0
3   4.0      60.0       50.0      77.0
4   5.0      63.0       41.0      89.0
5   6.0      75.0       54.0      85.0
6   7.0      60.0       51.0      96.0
7   8.0      77.0       64.0     105.0

In [10]:
mean_imp = SimpleImputer(strategy = 'mean',fill_value=60).set_output(transform="pandas")
mean_imp.fit(job)

SimpleImputer(fill_value=60)

In [11]:
mean_imp.fit_transform(job)

   S_No   Computer  Marketing  Engineer
0   1.0  84.000000  55.000000      75.0
1   2.0  90.000000  53.000000      70.0
2   3.0  63.000000  52.571429      88.0
3   4.0  75.333333  50.000000      77.0
4   5.0  63.000000  41.000000      89.0
5   6.0  75.000000  54.000000      85.0
6   7.0  75.333333  51.000000      96.0
7   8.0  77.000000  64.000000     105.0

In [12]:
median_imp = SimpleImputer(strategy = 'median',fill_value=60).set_output(transform="pandas")
median_imp.fit(job)

SimpleImputer(fill_value=60, strategy='median')

In [13]:
median_imp.fit_transform(job)

   S_No  Computer  Marketing  Engineer
0   1.0      84.0       55.0      75.0
1   2.0      90.0       53.0      70.0
2   3.0      63.0       53.0      88.0
3   4.0      76.0       50.0      77.0
4   5.0      63.0       41.0      89.0
5   6.0      75.0       54.0      85.0
6   7.0      76.0       51.0      96.0
7   8.0      77.0       64.0     105.0

In [14]:
os.chdir("C:/Users/PGCP-AI/Downloads/Machine-Learning-master/Machine-Learning-master")

In [27]:
housing = pd.read_csv('Housing.csv')
housing

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [28]:
X=chem.drop("Yield",axis=1)
y=chem['Yield']

In [33]:
median_imp = SimpleImputer(strategy = 'median',fill_value=60).set_output(transform="pandas")

X_trn_imp=median_imp.fit_transform(X_train)

# X_tst_imp=mean_imp.fit_transform(X_test)
X_tst_imp = median_imp.transform(X_test)

lr = LinearRegression()

# lr.fit(X_train,y_train)
lr.fit(X_trn_imp, y_train)

y_pred=lr.predict(X_tst_imp)
print("R2=",r2_score(y_test,y_pred))

R2= -4.10570782574536

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=26) 
mean_imp = SimpleImputer(strategy = 'mean',fill_value=60).set_output(transform="pandas")
X_trn_imp=med_imp.fit_transform(X_train)

# X_tst_imp=mean_imp.fit_transform(X_test)
X_tst_imp = med_imp.transform(X_test)

lr = LinearRegression()

# lr.fit(X_train,y_train)
lr.fit(X_trn_imp, y_train)

y_pred=lr.predict(X_tst_imp)
print("R2=",r2_score(y_test,y_pred))

NameError: name 'med_imp' is not defined