In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression,ElasticNet
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error,root_mean_squared_error,confusion_matrix,roc_auc_score,log_loss
from sklearn.metrics import f1_score,accuracy_score,recall_score,precision_score,classification_report
import os
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder, MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor

import datetime as dt

In [2]:
housing = pd.read_csv(r"../Datasets/Housing.csv")
housing

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [3]:
X = housing.drop('price',axis=1)
y=housing['price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=26)

In [23]:
X_trn_ohe = trans.fit_transform(X_train)
X_tst_ohe = trans.transform(X_test)

In [5]:
from sklearn.compose import make_column_selector,ColumnTransformer

ohe=OneHotEncoder(sparse_output=False,drop="first").set_output(transform="pandas")
trans = ColumnTransformer(
    transformers=[("OHE", ohe,make_column_selector(dtype_include=object))],remainder="passthrough",
    verbose_feature_names_out=False).set_output(transform="pandas")

In [24]:
ks=[1,2,3,4,5,6,7,8,9,10]
scores = []
for k in ks:
    knn= KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_trn_ohe, y_train)
    y_pred_prob = knn.predict(X_tst_ohe)
    scores.append([k, r2_score(y_test, y_pred_prob)])
df_scores = pd.DataFrame(scores, columns=['ks', 'r2_score'])
df_scores.sort_values('r2_score', ascending=False)

   ks  r2_score
3   4  0.686443
4   5  0.677831
2   3  0.670443
5   6  0.664499
6   7  0.655339
7   8  0.654481
8   9  0.653360
9  10  0.650433
0   1  0.600760
1   2  0.585665

In [7]:
# STANDARD SCALING

In [25]:
scalar=StandardScaler().set_output(transform="pandas")
scalar.fit(X_trn_ohe)
X_trn_scl=scalar.transform(X_trn_ohe)
X_tst_scl=scalar.transform(X_tst_ohe)

In [26]:
ks=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
scores = []
for k in ks:
    knn= KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_trn_scl, y_train)
    y_pred_prob = knn.predict(X_tst_scl)
    scores.append([k, r2_score(y_test, y_pred_prob)])
df_scores = pd.DataFrame(scores, columns=['ks', 'r2_score'])
df_scores.sort_values('r2_score', ascending=False)

    ks  r2_score
4    5  0.709663
7    8  0.698523
5    6  0.695438
6    7  0.692776
2    3  0.692301
8    9  0.691397
3    4  0.687542
9   10  0.684710
10  11  0.679353
11  12  0.669135
13  14  0.653043
12  13  0.652452
1    2  0.649537
14  15  0.641319
0    1  0.618293

In [10]:
### min max scaling

In [27]:
scalar=MinMaxScaler().set_output(transform="pandas")
scalar.fit(X_trn_ohe)
X_trn_scl=scalar.transform(X_trn_ohe)
X_tst_scl=scalar.transform(X_tst_ohe)

In [29]:
ks=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
scores = []
for k in ks:
    knn= KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_trn_scl, y_train)
    y_pred_prob = knn.predict(X_tst_scl)
    scores.append([k, r2_score(y_test, y_pred_prob)])
df_scores = pd.DataFrame(scores, columns=['ks', 'r2_score'])
df_scores.sort_values('r2_score', ascending=False)

    ks  r2_score
5    6  0.686453
6    7  0.681397
4    5  0.678191
7    8  0.677849
8    9  0.674605
9   10  0.671331
2    3  0.661415
10  11  0.658691
3    4  0.654668
11  12  0.652885
12  13  0.636796
13  14  0.625914
14  15  0.611317
1    2  0.594986
0    1  0.565138

In [30]:
concrete = pd.read_csv(r"../Datasets/Concrete_Data.csv")
concrete

,Cement,Blast,Fly,Water,Superplasticizer,Coarse,Fine,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.40

In [31]:
X = concrete.drop('Strength',axis=1)
y = concrete['Strength']

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=26)

In [33]:
X_trn_ohe = trans.fit_transform(X_train)
X_tst_ohe = trans.transform(X_test)

In [34]:
from sklearn.compose import make_column_selector,ColumnTransformer

ohe=OneHotEncoder(sparse_output=False,drop="first").set_output(transform="pandas")
trans = ColumnTransformer(
    transformers=[("OHE", ohe,make_column_selector(dtype_include=object))],remainder="passthrough",
    verbose_feature_names_out=False).set_output(transform="pandas")

In [35]:
ks=[1,2,3,4,5,6,7,8,9,10]
scores = []
for k in ks:
    knn= KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_trn_ohe, y_train)
    y_pred_prob = knn.predict(X_tst_ohe)
    scores.append([k, r2_score(y_test, y_pred_prob)])
df_scores = pd.DataFrame(scores, columns=['ks', 'r2_score'])
df_scores.sort_values('r2_score', ascending=False)

   ks  r2_score
3   4  0.686443
4   5  0.677831
2   3  0.670443
5   6  0.664499
6   7  0.655339
7   8  0.654481
8   9  0.653360
9  10  0.650433
0   1  0.600760
1   2  0.585665

In [36]:
scalar=StandardScaler().set_output(transform="pandas")
scalar.fit(X_trn_ohe)
X_trn_scl = scalar.transform(X_trn_ohe)
X_tst_scl = scalar.transform(X_tst_ohe)

In [37]:
ks=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
scores = []
for k in ks:
    knn= KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_trn_scl, y_train)
    y_pred = knn.predict(X_tst_scl)
    scores.append([k, r2_score(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['ks', 'r2_score'])
df_scores.sort_values('r2_score', ascending=False)

    ks  r2_score
4    5  0.709663
7    8  0.698523
5    6  0.695438
6    7  0.692776
2    3  0.692301
8    9  0.691397
3    4  0.687542
9   10  0.684710
10  11  0.679353
11  12  0.669135
13  14  0.653043
12  13  0.652452
1    2  0.649537
14  15  0.641319
0    1  0.618293

In [38]:
scalar=MinMaxScaler().set_output(transform="pandas")
scalar.fit(X_trn_ohe)
X_trn_scl=scalar.transform(X_trn_ohe)
X_tst_scl=scalar.transform(X_tst_ohe)

In [39]:
ks=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
scores = []
for k in ks:
    knn= KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_trn_scl, y_train)
    y_pred_prob = knn.predict(X_tst_scl)
    scores.append([k, r2_score(y_test, y_pred_prob)])
df_scores = pd.DataFrame(scores, columns=['ks', 'r2_score'])
df_scores.sort_values('r2_score', ascending=False)

    ks  r2_score
5    6  0.686453
6    7  0.681397
4    5  0.678191
7    8  0.677849
8    9  0.674605
9   10  0.671331
2    3  0.661415
10  11  0.658691
3    4  0.654668
11  12  0.652885
12  13  0.636796
13  14  0.625914
14  15  0.611317
1    2  0.594986
0    1  0.565138