In [24]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression,ElasticNet
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error,root_mean_squared_error,confusion_matrix,roc_auc_score,log_loss
from sklearn.metrics import f1_score,accuracy_score,recall_score,precision_score,classification_report
from tqdm import tqdm
import os
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder, MinMaxScaler,PolynomialFeatures
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor
import datetime as dt
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis,QuadraticDiscriminantAnalysis
from sklearn.naive_bayes import BernoulliNB,GaussianNB
from sklearn.svm import SVC

In [2]:
sonar = pd.read_csv(r"../Datasets/sonar.csv")
sonar

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V52,V53,V54,V55,V56,V57,V58,V59,V60,Class
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,0.0187,0.0346,0.0168,0.0177,0.0393,0.1630,0.2028,0.1694,0.2328,0.2684,...,0.0116,0.0098,0.0199,0.0033,0.0101,0.0065,0.0115,0.0193,0.0157,M
204,0.0323,0.0101,0.0298,0.0564,0.0760,0.0958,0.0990,0.1018,0.1030,0.2154,...,0.0061,0.0093,0.0135,0.0063,0.0063,0.0034,0.0032,0.0062,0.0067,M
205,0.0522,0.0437,0.0180,0.0292,0.0351,0.1171,0.1257,0.1178,0.1258,0.2529,...,0.0160,0.0029,0.0051,0.0062,0.0089,0.0140,0.0138,0.0077,0.0031,M
206,0.0303,0.0353,0.0490,0.0608,0.0167,0.1354,0.1465,0.1123,0.1945,0.2354,...,0.0086,0.0046,0.0126,0.0036,0.0035,0.0034,0.0079,0.0036,0.0048,M
207,0.0260,0.0363,0.0136,0.0272,0.0214,0.0338,0.0655,0.1400,0.1843,0.2354,...,0.0146,0.0129,0.0047,0.0039,0.0061,0.0040,0.0036,0.0061,0.0115,M

### svm with linear kernel and accuracy score

In [3]:
X = sonar.drop('Class', axis=1)
print("x : ",X)
y = sonar['Class']
print("y: ",y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state=26, stratify= sonar['Class'])

x :           V1      V2      V3      V4      V5      V6      V7      V8      V9  \
0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564
..      ...     ...     ...     ...     ...     ...     ...     ...     ...
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945
207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843

        V10  ...     V51     V52     V53     V54     V55     V56     V57  \
0    0.2111  ...  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180
1    0.2872  ...  0.0125  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140
2    0.6194  ...  0.0033  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316
3    0.1264  ...  0.0241  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050
4    0.4459  ...  0.0156  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072
..      ...  ...     ...     ...     ...     ...     ...     ...     ...
203  0.2684  ...  0.0203  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065
204  0.2154  ...  0.0051  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034
205  0.2529  ...  0.0155  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140
206  0.2354  ...  0.0042  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034
207  0.2354  ...  0.0181  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040

        V58     V59     V60
0    0.0084  0.0090  0.0032
1    0.0049  0.0052  0.0044
2    0.0164  0.0095  0.0078
3    0.0044  0.0040  0.0117
4    0.0048  0.0107  0.0094
..      ...     ...     ...
203  0.0115  0.0193  0.0157
204  0.0032  0.0062  0.0067
205  0.0138  0.0077  0.0031
206  0.0079  0.0036  0.0048
207  0.0036  0.0061  0.0115

[208 rows x 60 columns]
y:  0      R
1      R
2      R
3      R
4      R
      ..
203    M
204    M
205    M
206    M
207    M
Name: Class, Length: 208, dtype: str

In [4]:
Cs = np.linspace(0.001, 1, 20)
scores = []
for c in Cs:
    svm = SVC(kernel='linear', C=c)
    svm.fit(X_train, y_train)
    y_pred = svm.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    scores.append((c,accuracy))
print("Accuracy:", accuracy)

Accuracy: 0.8412698412698413

In [5]:
df_scores = pd.DataFrame(scores, columns=['c','accuracy'])
df_scores.sort_values( 'accuracy', ascending=False).head()

           c  accuracy
19  1.000000   0.84127
18  0.947421   0.84127
17  0.894842   0.84127
16  0.842263   0.84127
15  0.789684   0.84127

### svm with log loss

In [6]:
Cs = np.linspace(0.001, 1, 20)
scores = []
for c in Cs:
    svm = SVC(kernel='linear', C=c, probability=True,random_state=26)
    svm.fit(X_train, y_train)
    y_pred_prob = svm.predict_proba(X_test)
    accuracy = log_loss(y_test, y_pred_prob)
    scores.append([c,accuracy])

In [7]:
df_scores = pd.DataFrame(scores, columns=['c','log_loss'])
df_scores.sort_values( 'log_loss', ascending=True).head()

           c  log_loss
2   0.106158  0.480810
13  0.684526  0.484304
14  0.737105  0.485563
12  0.631947  0.485822
16  0.842263  0.487561

### Polynomial Kernel: Tested curved boundaries with different degrees (2, 3, and 4).

In [8]:
X = sonar.drop('Class', axis=1)
print("x : ",X)
y = sonar['Class']
print("y: ",y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state=26, stratify= sonar['Class'])

x :           V1      V2      V3      V4      V5      V6      V7      V8      V9  \
0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564
..      ...     ...     ...     ...     ...     ...     ...     ...     ...
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945
207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843

        V10  ...     V51     V52     V53     V54     V55     V56     V57  \
0    0.2111  ...  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180
1    0.2872  ...  0.0125  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140
2    0.6194  ...  0.0033  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316
3    0.1264  ...  0.0241  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050
4    0.4459  ...  0.0156  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072
..      ...  ...     ...     ...     ...     ...     ...     ...     ...
203  0.2684  ...  0.0203  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065
204  0.2154  ...  0.0051  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034
205  0.2529  ...  0.0155  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140
206  0.2354  ...  0.0042  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034
207  0.2354  ...  0.0181  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040

        V58     V59     V60
0    0.0084  0.0090  0.0032
1    0.0049  0.0052  0.0044
2    0.0164  0.0095  0.0078
3    0.0044  0.0040  0.0117
4    0.0048  0.0107  0.0094
..      ...     ...     ...
203  0.0115  0.0193  0.0157
204  0.0032  0.0062  0.0067
205  0.0138  0.0077  0.0031
206  0.0079  0.0036  0.0048
207  0.0036  0.0061  0.0115

[208 rows x 60 columns]
y:  0      R
1      R
2      R
3      R
4      R
      ..
203    M
204    M
205    M
206    M
207    M
Name: Class, Length: 208, dtype: str

In [9]:
Cs = np.linspace(0.001, 5, 20)
Ds=[2,3,4]
scores = []
for c in Cs:
    for d in Ds:
        svm = SVC(kernel='poly', C=c, probability=True,random_state=26,degree=d)
        svm.fit(X_train, y_train)
        y_pred_prob = svm.predict_proba(X_test)
        scores.append([c,d,log_loss(y_test, y_pred_prob)])

In [10]:
df_scores = pd.DataFrame(scores, columns=['c','d','log_loss'])
df_scores.sort_values( 'log_loss', ascending=True).head()

           c  d  log_loss
59  5.000000  4  0.390880
56  4.736895  4  0.390901
53  4.473789  4  0.391032
50  4.210684  4  0.391403
41  3.421368  4  0.391449

### RBF (Radial Basis Function) Kernel: Tested a highly flexible boundary that uses a "distance" logic (Gamma).

In [ ]:
Cs = np.linspace(0.001, 5, 20)
Gs = np.linspace(0.001,5,20)

scores = []
for c in Cs:
    for g in Gs:
        svm = SVC(kernel='rbf', C=c, probability=True,random_state=26,gamma = g)
        svm.fit(X_train, y_train)
        y_pred_prob = svm.predict_proba(X_test)
        scores.append([c,g,log_loss(y_test, y_pred_prob)])

df_scores = pd.DataFrame(scores, columns=['c',g,'log_loss'])
df_scores.sort_values( 'log_loss', ascending=True).head()

### sigmoid

In [13]:
Cs = np.linspace(0.001, 5, 20)
coefs = np.linspace(-5, 5, 20)

scores = []
for c in Cs:
    for cf in coefs: 
        svm = SVC(kernel='sigmoid', C=c, probability=True, random_state=26, coef0=cf)
        svm.fit(X_train, y_train)
        y_pred_prob = svm.predict_proba(X_test)
        scores.append([c, cf, log_loss(y_test, y_pred_prob)])

df_scores = pd.DataFrame(scores, columns=['c', 'coef0', 'log_loss'])

df_scores.sort_values('log_loss', ascending=True).head()

            c     coef0  log_loss
384  5.000000 -2.894737  0.420820
364  4.736895 -2.894737  0.421167
344  4.473789 -2.894737  0.422775
304  3.947579 -2.894737  0.422984
284  3.684474 -2.894737  0.423297

### ON HR DATA

In [16]:
hr = pd.read_csv(r"../Datasets/HR_comma_sep.csv")
hr

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.10,0.77,6,247,4,0,1,0,sales,low
3,0.92,0.85,5,259,5,0,1,0,sales,low
4,0.89,1.00,5,224,5,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...,...
14990,0.40,0.57,2,151,3,0,1,0,support,low
14991,0.37,0.48,2,160,3,0,1,0,support,low
14992,0.37,0.53,2,143,3,0,1,0,support,low
14993,0.11,0.96,6,280,4,0,1,0,support,low
14994,0.37,0.52,2,158,3,0,1,0,support,low

In [17]:
X = hr.drop('left',axis=1)
y = hr['left']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=26, stratify=hr['left'])

In [18]:
# OneHotEncoder

In [34]:
ohe=OneHotEncoder(sparse_output=False,drop="first").set_output(transform="pandas")
trans = ColumnTransformer(
    transformers=[("OHE", ohe,make_column_selector(dtype_include=object))],remainder="passthrough",
    verbose_feature_names_out=False).set_output(transform="pandas")

X_trn_ohe = trans.fit_transform(X_train)
X_tst_ohe = trans.transform(X_test)

In [ ]:
from tqdm import tqdm

Cs = np.linspace(0.001, 1, 20)
scores = []
for c in tqdm(Cs):
    svm = SVC(kernel='linear', C=c, probability=True,random_state=26)
    svm.fit(X_trn_scl, y_train)
    y_pred_prob = svm.predict_proba(X_tst_scl)
    accuracy = log_loss(y_test, y_pred_prob)
    scores.append([c,accuracy])

df_scores = pd.DataFrame(scores, columns=['c','log_loss'])
df_scores.sort_values( 'log_loss', ascending=True).head()

### RBF (Radial Basis Function) Kernel: Tested a highly flexible boundary that uses a "distance" logic (Gamma).

In [ ]:
Cs = np.linspace(0.001, 5, 20)
Gs = np.linspace(0.001,5,20)

scores = []
for c in Cs:
    for g in Gs:
        svm = SVC(kernel='rbf', C=c, probability=True,random_state=26,gamma = g)
         svm.fit(X_trn_scl, y_train)
        y_pred_prob = svm.predict_proba(X_tst_scl)
        log_loss(y_test, y_pred_prob)
        scores.append([c,g,log_loss(y_test, y_pred_prob))

df_scores = pd.DataFrame(scores, columns=['c','log_loss'])
df_scores.sort_values( 'log_loss', ascending=True).head()

In [8]:
cancer=pd.read_csv(r"../Datasets/BreastCancer.csv")
cancer

,Code,Clump,UniCell_Size,Uni_CellShape,MargAdh,SEpith,BareN,BChromatin,NoemN,Mitoses,Class
0,61634,5,4,3,1,2,2,2,3,1,Benign
1,63375,9,1,2,6,4,10,7,7,2,Malignant
2,76389,10,4,7,2,2,8,6,1,1,Malignant
3,95719,6,10,10,10,8,10,7,10,7,Malignant
4,128059,1,1,1,1,2,5,5,1,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...
694,1369821,10,10,10,10,5,10,10,10,7,Malignant
695,1371026,5,10,10,10,4,10,5,6,3,Malignant
696,1371920,5,1,1,1,2,1,3,2,1,Benign
697,8233704,4,1,1,1,1,1,2,1,1,Benign
698,13454352,1,1,3,1,2,1,2,1,1,Benign

In [25]:
X = cancer.drop(['Code','Class'],axis=1)
y=cancer['Class']
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3,random_state=26,stratify = cancer['Class'])

In [26]:
from sklearn.compose import make_column_selector
from sklearn.compose import  ColumnTransformer

ohe=OneHotEncoder(sparse_output=False,drop="first").set_output(transform="pandas")
trans = ColumnTransformer(
    transformers=[("OHE", ohe,make_column_selector(dtype_include=object))],remainder="passthrough",
    verbose_feature_names_out=False).set_output(transform="pandas")

X_trn_ohe = trans.fit_transform(X_train)
X_tst_ohe = trans.transform(X_test)

In [32]:
scalar = StandardScaler()
X_trn_scl = scalar.fit_transform(X_trn_ohe)
X_tst_scl = scalar.transform(X_tst_ohe)

In [36]:
from tqdm import tqdm

Cs = np.linspace(0.001, 1, 20)
scores = []
for c in tqdm(Cs):
    svm = SVC(kernel='linear', C=c, probability=True,random_state=26)
    svm.fit(X_trn_scl, y_train)
    y_pred_prob = svm.predict_proba(X_tst_scl)
    accuracy = log_loss(y_test, y_pred_prob)
    scores.append([c,accuracy])

df_scores = pd.DataFrame(scores, columns=['c','log_loss'])
df_scores.sort_values( 'log_loss', ascending=True).head()

  0%|                                                                                           | 0/20 [00:00<?, ?it/s]

 30%|████████████████████████▉                                                          | 6/20 [00:00<00:00, 59.48it/s]

 70%|█████████████████████████████████████████████████████████▍                        | 14/20 [00:00<00:00, 69.06it/s]

100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 68.88it/s]

           c  log_loss
7   0.369053  0.101754
9   0.474211  0.101819
13  0.684526  0.101850
10  0.526789  0.101851
14  0.737105  0.101867

In [41]:
Cs = np.linspace(0.001, 5, 20)
Gs = np.linspace(0.001,5,20)

scores = []
for c in Cs:
    for g in Gs:
        svm = SVC(kernel='rbf', C=c, probability=True,random_state=26,gamma = g)
        svm.fit(X_trn_scl, y_train)
        y_pred_prob = svm.predict_proba(X_tst_scl)
        log_loss(y_test, y_pred_prob)
        scores.append([c,g,log_loss(y_test, y_pred_prob)])

df_scores = pd.DataFrame(scores, columns=['c','g','log_loss'])
df_scores.sort_values( 'log_loss', ascending=True).head()

            c      g  log_loss
380  5.000000  0.001  0.099073
360  4.736895  0.001  0.099305
340  4.473789  0.001  0.099853
320  4.210684  0.001  0.100997
300  3.947579  0.001  0.101682